Voter's Block: 	The attempt, however futile, to register dissent with the current political system by simply not voting. 		-- Douglas Coupland, "Generation X: Tales for an Accelerated 		   Culture"

diff --git a/Bash/Sourced/cd b/Bash/Sourced/cd
--- a/Bash/Sourced/cd
+++ b/Bash/Sourced/cd
@@ -17,7 +17,15 @@ cd() #@ Change directory, saving location on the directory stack
     if [ $? -ne 0 ]
     then    
         # Let the builtin make an attempt..
-        builtin cd "$1"
+        builtin cd "$1" 1&> /dev/null
+        if [ $? -ne 0 ]
+        then    
+            pushd "$(dirname "${1}")"
+        fi
+        if [ $? -ne 0 ]
+        then    
+            printf "Could not cd into %s\n" "${1}" > /dev/fd/1
+        fi
     fi
 
 
