pdf can say if file is not found

diff --git a/Bash/pdf b/Bash/pdf
--- a/Bash/pdf
+++ b/Bash/pdf
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+#@ DESCRIPTION: print error msg and exit with a given ret value
+die() #@ USAGE: die STAUTS [MESSAGE]
+{
+	error=$1
+	shift
+	[ -n "$*" ] && printf "%s\n" "$*" >&2
+	exit "$error"
+}
+
 function pdf()
 {
 	if [ -z "${1}" ]
@@ -10,6 +19,11 @@ function pdf()
 
 	eval local file='"${1}"'
 
+    if [ ! -e ${file} ]
+    then
+        die 1 "${file} not found"
+    fi
+
 	if [ "${file##*.}" == "doc" ]
 	then
 		unoconv -fpdf "${file}";
@@ -18,7 +32,7 @@ function pdf()
 		exit
 	fi
 
-	zathura "${file}" &
-} 2>/dev/null
+	xdg-open "${file}" &
+} #2>/dev/null
 
 pdf "${1}"
